### ISSUE TITLE
Example ENV

### ISSUE THREAD

**Issue by muhamdaily** [rakibtweets/dev_overflow_nextjs13#1]
Hello, can you provide an ENV example?

**Comment by rakibtweets** [comment]
You can see Readme.md file,  where I have provided EVN variable, Please use your own ENV variable to run this project.

**Comment by muhamdaily** [comment]
```
NEXT_PUBLIC_SERVER_URL=
...
NEXT_PUBLIC_RAPID_API_KEY=
```

I want to see that env above what value? Because I don't understand the ENV above, I have filled in the other ENVs

**Comment by rakibtweets** [comment]
NEXT_PUBLIC_SERVER_URL it's a server URL where code is running, this can be localhost or deployed public url.

NEXT_PUBLIC_RAPID_API_KEY is from https://rapidapi.com/ for job search api.

**Comment by muhamdaily** [comment]
Ah ok, I understand but I got an error on the MongoDB URL

```
MongoDB is connected
MongoDB connection failed Error: querySrv ENOTFOUND _mongodb._tcp.mimobot.bwvqjdu.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:275:17)
    at QueryReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: undefined,
  code: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.mimobot.bwvqjdu.mongodb.net'
}

MongooseError: Operation `questions.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
 ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
MongooseError: Operation `questions.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
 ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
digest: "865127199"
 ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
 ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
digest: "865127199"
```

**Comment by muhamdaily** [comment]
And if I may ask, what endpoints do you take on the clerk webhook?

`NEXT_CLERK_WEBHOOK_SECRET=`

**Comment by rakibtweets** [comment]
> And if I may ask, what endpoints do you take on the clerk webhook?
> 
> `NEXT_CLERK_WEBHOOK_SECRET=`
You need to learn what webhook is. Its a event listener for clerk authentication and user profile management such as user profile update, delete, create etc.

**Comment by rakibtweets** [comment]
> Ah ok, I understand but I got an error on the MongoDB URL
> 
> ```
> MongoDB is connected
> MongoDB connection failed Error: querySrv ENOTFOUND _mongodb._tcp.mimobot.bwvqjdu.mongodb.net
>     at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:275:17)
>     at QueryReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
>   errno: undefined,
>   code: 'ENOTFOUND',
>   syscall: 'querySrv',
>   hostname: '_mongodb._tcp.mimobot.bwvqjdu.mongodb.net'
> }
> 
> MongooseError: Operation `questions.find()` buffering timed out after 10000ms
>     at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
>  ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
>     at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
> MongooseError: Operation `questions.find()` buffering timed out after 10000ms
>     at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
>  ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
>     at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
> digest: "865127199"
>  ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
>     at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
>  ⨯ Internal error: MongooseError: Operation `questions.find()` buffering timed out after 10000ms
>     at Timeout.<anonymous> (D:\development\Apps\community\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
> digest: "865127199"
> ```
It's a mongodb connection error on your side, please check your connection URL and Database accesspoint.

**Comment by muhamdaily** [comment]
Thank you very much for your help, I'll try to check it out
